# _config.yml

# 站点基本配置
title: My Blog
subtitle: A Hexo blog
author: $USER
language: en
timezone: Asia/Shanghai

# 主题配置
theme: diaspora

# 网站 URL 配置
url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
root: /

# 其他 Hexo 配置
deploy:
  type: git
  repo: https://github.com/${{ github.repository_owner }}/{{ github.event.repository.name }}.git
