name: Deploy static content to GitPages
on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      ISITE_VERSION: v0.1.3
      ZOLA_VERSION: v0.19.2
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      # BASE_URL: https://blog.yihong0618.me # change to your own domain
      # Change to below if you are using GitHub Pages
      BASE_URL: https://${{ github.repository_owner }}.github.io/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Generate markdown
        run: |
          npm install -g hexo-cli
          npm create kira-hexo@latest output
          cd output && sudo rm -rf node_modules
          npm install
          hexo clean && hexo generate 
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'output/public'
      - name: check action
        run: |
          ls output
          echo "这样"
          ls output/public
          echo "这样"
          ls 
          echo "这样"
          ls action
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
